#pragma once

typedef unsigned char BYTE;

constexpr auto BAC_LPC_PORT_NAME = L"\\RPC Control\\BACControl";

enum class LPC_CLIENT_TYPE : BYTE
{
    CONTROL,
    INJECTED,
    LPC_CLIENT_TYPE_MAX
};

enum class LPC_MESSAGE_CONTROL : BYTE
{
    REPLY_AS_CALLBACK,
    IGNORE_REPLY,
    LPC_MESSAGE_CONTROL_MAX
};

enum class LPC_MESSAGE_TYPE : BYTE
{
    HEART_BEAT,
    LOG_TRANSMISSION,
    LPC_MESSAGE_TYPE_MAX
};

enum class LPC_REPLY_CONTROL : BYTE
{
    PROCEED,
    FAILED,
    LPC_REPLY_CONTROL_MAX
};

typedef struct _LPC_CLIENT_CONNECT_INFORMATION {
    LPC_CLIENT_TYPE     ClientType;
} LPC_CLIENT_CONNECT_INFORMATION, *PLPC_CLIENT_CONNECT_INFORMATION;

typedef struct _LPC_MESSAGE_INFORMATION {
    LPC_MESSAGE_CONTROL MessageControl;
    LPC_MESSAGE_TYPE    MessageType;
} LPC_MESSAGE_INFORMATION, *PLPC_MESSAGE_INFORMATION;

typedef struct _LPC_REPLY_MESSAGE_INFORMATION {
    LPC_REPLY_CONTROL   ReplyControl;
} LPC_REPLY_MESSAGE_INFORMATION, *PLPC_REPLY_MESSAGE_INFORMATION;
